### ISSUE TITLE
mapkit tile overlay CGImageSourceCreateWithData error

### ISSUE THREAD

**Issue by brianhyper** [mapbox/mbxmapkit#132]
I can't find many answers to this error on the web...

Here's the error that I get:
[8225] <Error>: ImageIO: CGImageSourceCreateWithData data parameter is nil

It looks like in SDK8, the tile overlay generates errors... but is it the mbxmapkit or the apple MapKit? and is this error has been reported somewhere?

Thx!

Brian

**Comment by gtasko** [comment]
I used pod 'MBXMapKit' in my podfile and I can't seem to find the MBXRasterTileRenderer.
Is there something I should check?

I get the <Error>: ImageIO: CGImageSourceCreateWithData data parameter is nil both in iPhone 6 simulator and iOS 8.1 iPhone 6 device.

Also, can I avoid the refresh that is doing when I drag the map around? I should use caching to improve performance?

Another problem is that we don't have access to set the accesstoken, will this introduce problems using a custom layout to MapKit?

**Comment by incanus** [comment]
@gtasko This is not yet released (see #136; it's close) so you'll have to reference the `132-renderer` branch in your `Podfile` in order to pull this in.

**Comment by gtasko** [comment]
OK, thanks, I'll wait for the release then.

Do you know about the setAccessToken question? Why the method is not exposed to the interface file?

**Comment by incanus** [comment]
Yes, it's related. See the [changelog](https://github.com/mapbox/mbxmapkit/blob/master/CHANGELOG.md). It will come back very soon with support for `v4`. Right now `v3` will automatically be used.

**Comment by gtasko** [comment]
OK, thanks for the response, we will wait for the next release version.

**Comment by suraj-aahlaad** [comment]
How to calculate the size of the selected area of the map before downloading i am using MBXMapKit SDK any one can help me how to calculate the size of the map before downloading the map.
