### ISSUE TITLE
Crash in MKTileOverlayRenderer

### ISSUE THREAD

**Issue by sunilvignesh** [mapbox/mbxmapkit#144]
Not able to reproduce this, but this occurs frequently in production.

Thread 16 Crashed:
0   libsystem_platform.dylib             0x0000000195fcd390 _platform_memmove + 320
1   libsystem_c.dylib                    0x0000000195ec8424 __memcpy_chk + 28
2   ImageIO                              0x000000018621198c _CGImageSourceBindToPlugin + 312
3   ImageIO                              0x00000001862117d4 CGImageSourceGetCount + 108
4   MapKit                               0x000000018716d6bc -[MKTileOverlayRenderer drawMapRect:zoomScale:inContext:] + 420
5   MapKit                               0x0000000187164230 __47-[MKOverlayRenderer overlay:drawKey:inContext:]_block_invoke + 448
6   MapKit                               0x000000018716430c _worldsForBounds19338 + 68
7   MapKit                               0x000000018716404c -[MKOverlayRenderer overlay:drawKey:inContext:] + 168
8   VectorKit                            0x0000000192454278 __40-[VKRasterOverlayTileSource _queueDraw:]_block_invoke + 408
9   libdispatch.dylib                    0x0000000195df93ac _dispatch_call_block_and_release + 20
10  libdispatch.dylib                    0x0000000195df936c _dispatch_client_callout + 12
11  libdispatch.dylib                    0x0000000195e0540c _dispatch_root_queue_drain + 1148
12  libdispatch.dylib                    0x0000000195e0675c _dispatch_worker_thread3 + 104
13  libsystem_pthread.dylib              0x0000000195fd52e4 _pthread_wqthread + 812
14  libsystem_pthread.dylib              0x0000000195fd4fa8 start_wqthread + 0

**Comment by incanus** [comment]
Yep, this is being tackled over in #136 right now.
