### ISSUE TITLE
React Native Module

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mbxmapkit#158]
Definitely a blue sky/pet project, just putting it on the table:  `npm install mbxmapkit-react-native`

It would be awesome if you could could work with mbxmapkit in a react native project. Creating a native module in react-native does not look to involved, [docs](http://facebook.github.io/react-native/docs/nativemodulesios.html#content).

/cc @incanus @edenh @tmcw @1ec5

**Comment by incanus** [comment]
MBX is definitely our lightest toolkit, since it layers on Apple's MapKit. Would be the easiest dive.
