### ISSUE TITLE
BSD license

### ISSUE THREAD

**Issue by mackuba** [mapbox/mbxmapkit#159]
Hi,

just to clarify, since you use the BSD license which says that reproductions in binary form must include the author's copyright info in the documentation - I'm assuming you don't actually require any such attribution in apps? (You might consider switching to MIT which only requires keeping the copyright info with the code.)

**Comment by incanus** [comment]
We do require attribution in apps, like someplace in the about view or a credits view, or even the settings bundle.

**Comment by mackuba** [comment]
But not necessarily in the form of "the above copyright notice, this list of conditions and the following disclaimer"? :)

**Comment by incanus** [comment]
Good point. I will leave this open and we can have some internal discussion about the best course here. /cc @michaelsteffen

**Comment by mackuba** [comment]
The way I see it, using the code and using the service are two separate things (or even three if you count the maps). The license in question is about the code in this repo. Regardless of the code license, if you use it to connect to the service (and if you have an account on the service, which you need to have to do anything useful with the code), then you also need to agree to the terms of the service separately. The only case when the license for the code could be important by itself would be when someone took the client code and reused it for some completely different purpose (e.g. to write their own MapKit extension that does something different).
