### ISSUE TITLE
Crashes in [VKRasterOverlayTileSource invalidateRect:level:] and [VKTileKeyMap enumerateKeysAndObjectsUsingBlock:]

### ISSUE THREAD

**Issue by s219** [mapbox/mbxmapkit#165]
Now that I have mbxmapkit offline maps running in my app, I am seeing frequent crashes when zooming/panning around the map with an offline tile overlay.  Sometimes the app will crash just sitting there with the offline tile overlay on the map.  Crashes seem to be happening around calls to [VKRasterOverlayTileSource invalidateRect:level:] and [VKTileKeyMap enumerateKeysAndObjectsUsingBlock:].  I see the problem in the sample app as well, if I spend enough time zooming/panning around.

Though I cannot confirm with data, the problem seems to happen sooner when I have a tile overlay formed with a limited range of zoom levels (for example only levels 15-20 downloaded) compared to an overlay with all zoom levels (0-20).  That may be a clue, or could be related to some other factor.

I am seeing the problem on both a device with iOS 7.1.1 and a device with iOS 8.2.

I had previously been testing the app with online MapBox tiles for over 8 months, and it was solid the whole time.  So I think it's safe to say this new issue is related to displaying offline tiles.

Any suggestions how to proceed?

thanks,
219

**Comment by meierjo** [comment]
I've been seeing the same type of issue.  Sample dump included below.  Issue happens randomly on a offline map screen I have in my app.

Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x0000000195243bd0 objc_msgSend + 16
1  VectorKit                      0x0000000191c09dfc __50-[VKRasterOverlayTileSource invalidateRect:level:]_block_invoke_2 + 60
2  VectorKit                      0x00000001918bca78 -[VKTileKeyMap enumerateKeysAndObjectsUsingBlock:] + 76
3  VectorKit                      0x00000001918bca04 -[VKTilePool enumerateKeysAndObjectsUsingBlock:] + 96
4  VectorKit                      0x0000000191c09d58 __50-[VKRasterOverlayTileSource invalidateRect:level:]_block_invoke + 180
5  libdispatch.dylib              0x0000000195881994 _dispatch_call_block_and_release + 24
6  libdispatch.dylib              0x0000000195881954 _dispatch_client_callout + 16
7  libdispatch.dylib              0x000000019588620c _dispatch_main_queue_callback_4CF + 1608
8  CoreFoundation                 0x00000001840ca2ec __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
9  CoreFoundation                 0x00000001840c8394 __CFRunLoopRun + 1492
10 CoreFoundation                 0x0000000183ff51f4 CFRunLoopRunSpecific + 396
11 GraphicsServices               0x000000018d3276fc GSEventRunModal + 168
12 UIKit                          0x000000018898610c UIApplicationMain + 1488
13 AcquiSIGN                      0x00000001000360f8 main (main.m:16)
14 libdyld.dylib                  0x00000001958aea08 start + 4

**Comment by incanus** [comment]
Closing in favor of https://github.com/mapbox/mbxmapkit/issues/153.
