### ISSUE TITLE
Swift: MGLMultiPoint should use Int for pointCount

### ISSUE THREAD

**Issue by quicklywilliam** [mapbox/mbxmapkit#169]
See https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKMultiPoint_class/index.html#//apple_ref/occ/instp/MKMultiPoint/pointCount

MKMultiPoint uses NSUInteger in Obj-c land, but Int for Swift. MGLMultiPoint uses Uint in Swift.

**Comment by 1ec5** [comment]
This issue belongs in mapbox/mapbox-gl-native. This repository is for [MBXMapKit](https://www.mapbox.com/mbxmapkit/).

**Comment by quicklywilliam** [comment]
Whoops, my bad! Will refile there.

**Comment by quicklywilliam** [comment]
For reference: https://github.com/mapbox/mapbox-gl-native/issues/1878
