### ISSUE TITLE
deprecate repo in favor of GL

### ISSUE THREAD

**Issue by incanus** [mapbox/mbxmapkit#172]
- [x] Update repo description
- [x] Update `CONTRIBUTING.md`
- [x] Update `README.md`
- [x] Update `mb-pages` branch
- [x] Deprecate in CocoaPods
- [x] ~~Rename the repo?~~

**Comment by meierjo** [comment]
Should one start looking into migrating to GL ?  How long should one expect to be able to use mbxmapkit?  I'm in my final testing, looking to go to Production/app store within a few weeks....

**Comment by incanus** [comment]
MBXMapKit won't be going away — the repository will be here (possibly renamed, though) and will work on the `v4` Mapbox API. But yes, you should look into migrating to GL — Mapbox is moving from raster maps to vectors and Apple does not appear prepared to open up custom vector rendering atop MapKit.

**Comment by paulburd** [comment]
Early this year it was announced that maps created before 3/15/15 could continue to use the v3 API, and only maps created after 3/15/15 would be required to use v4. Is this still true? Is there a date when all maps will be required to use v4?

**Comment by incanus** [comment]
Hey @paulburd. There is not a date yet, but the GL-based library supports on `v4` and up, whereas this project and the old iOS SDK support `v3` still in software. 

The main difference with `v4` is the addition of access tokens, which we are trying to move everything over to for increased security and the ability to rotate upon exposure (primarily in JavaScript, whose source can be viewed). 

@willwhite Want to chime in here re: `v3` longitivtiy?

**Comment by willwhite** [comment]
@paulburd no plans to deprecate v3 any time soon - exiting maps will continue to work, but new maps are only available on v4.

**Comment by paulburd** [comment]
@incanus @willwhite Thanks for the info on the API. We should probably just switch to v4 as we're not ready to move to the other solutions yet. Just to confirm... "Mapbox GL", "Mapbox Mobile", and "OpenGL-based Mapbox iOS SDK" are all the same thing, right? Those are three names that all refer to [this](https://github.com/mapbox/mapbox-gl-native), right?

**Comment by incanus** [comment]
> Just to confirm... "Mapbox GL", "Mapbox Mobile", and "OpenGL-based Mapbox iOS SDK" are all the same thing, right? Those are three names that all refer to this, right?

Exactly. Part of the deprecation here is trying to reduce the terminology a bit and make this clearer :-)

**Comment by incanus** [comment]
All set!
