### ISSUE TITLE
MapID problem?

### ISSUE THREAD

**Issue by Heisenbean** [mapbox/mbxmapkit#175]
Hi!
I used `mbxmapkit` to download map,when i wrote these code
`    MBXOfflineMapDownloader *downloader = [MBXOfflineMapDownloader sharedOfflineMapDownloader];
    [downloader beginDownloadingMapID:@"pk.eyJ1IjoiaGVkb25nYmluIiwiYSI6ImNpaHEwN2Y1eTA0YTN0cG0yeXhvcGpqN3QifQ.lfyQkuZXBUssjTsUhwi8tQ" mapRegion:self.mapView.region minimumZ:12 maximumZ:18];`

I take exception breakpoint to debug,and break at `MBXMapKit.m`file in line 88,when i continue program execution 
i get this error in console log:
`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'pk.eyJ1IjoiaGVkb25nYmluIiwiYSI6ImNpaHEwN2Y1eTA0YTN0cG0yeXhvcGpqN3QifQ.lfyQkuZXBUssjTsUhwi8tQ'`

Is my `MapID` wrong?
I get this from [https://www.mapbox.com/studio/account/tokens/](https://www.mapbox.com/studio/account/tokens/)

**Comment by friedbunny** [comment]
That'll be your access token, not a map id. A vector map id, created with Mapbox Studio, looks like `mapbox://styles/heisenbean.somehashhere`. You cannot use this with mbxmapkit.

This framework (mbxmapkit) has been deprecated and is no longer supported. Check out the [new iOS SDK](https://mapbox.com/ios-sdk/) and [this guide](https://www.mapbox.com/help/first-steps-ios-sdk/) for how to get started.
