### ISSUE TITLE
Custom background color below tiles

### ISSUE THREAD

**Issue by blabus** [mapbox/mbxmapkit#74]
Is it possible to set a custom background color below the tile layer? I have a dark gray map style and currently it looks a bit odd to have the bright white with gray grid pattern visible before the dark tiles load. It'd be great to be able to set that background color to the same as my map tiles so the transition doesn't look quite as jarring.

**Comment by mackuba** [comment]
Hi,

I have the same problem, I would like to change the default yellowish color that's shown when the map is loading.

I've tried changing the map style to satellite, but now I see a gray grid that is replaced by yellowish tiles and then by the actual map tiles, so it seems to me that the yellowish background is something that comes from MapBox?

This is how it looks at the beginning (gray tiles are being replaced by yellowish tiles):

![screen shot 2015-04-28 at 15 02 46](https://cloud.githubusercontent.com/assets/28465/7370092/ddb3646a-edb7-11e4-8fe5-1ba4518a552e.png)

And this is how the final map tiles look:

![screen shot 2015-04-28 at 15 04 48](https://cloud.githubusercontent.com/assets/28465/7370116/066b3cf2-edb8-11e4-804e-1dc28050fd44.png)

**Comment by tomtaylor** [comment]
I'd love to know how to do this too - @mackuba did you solve it?

**Comment by tkrajacic** [comment]
The beige color is part of Apple's MapView. Unfortunately you can not customize it.
What you can do though is load single color tiles for the entire world as background.
