### ISSUE TITLE
Make an NSError error code for "account over limit"

### ISSUE THREAD

**Issue by ghost** [mapbox/mbxmapkit#76]
We should figure out how to recognize resource loading failures which are caused by a mapbox.com hosting account going over its limit, and we should have an NSError error code specifically for that situation.

I've never actually seen what happens on an over limit account, so I have no idea what the current code would do in that situation. I'm guessing the results would be mysterious and frustrating.

**Comment by wsnook** [comment]
@incanus Can this issue be closed now that v3 support was removed for the 0.7.0 release?

**Comment by incanus** [comment]
Hmm, I think `404` still applies to `v4` API. What I said above was in case this changed with `v4`, which it hasn't.
