### ISSUE TITLE
Discuss new API and offline maps work

### ISSUE THREAD

**Issue by ghost** [mapbox/mbxmapkit#79]
This issue is for discussing what needs to be done to polish the pile of commits from #73 into shape for merging into master. The changes implement a substantially revised API for MBXMapKit, including performance caching and offline maps. The offline maps part just recently hit the point of functionality, and now it needs some polish.

A couple notes:
1. I created the [mapbox/issue79](https://github.com/mapbox/mbxmapkit/tree/issue79) branch which squashes all the commits from the issue73 branch.
2. See https://github.com/mapbox/mbxmapkit/issues/73#issuecomment-41001033 for some initial thoughts from @incanus on what needs to happen next.

Todo:
- [x] Track down and fix any glitches with the sample app (in particular, check state transitions for offline maps)
- [x] Move the v030 iOS sample app to replace the old sample app
- [x] Figure out what to do about OS X support and the OS X sample app (see #78)
- [x] Revise the readme including a conceptual overview of how the new API works and how it's meant to be used. See [How Does Carmen Work?](https://github.com/mapbox/carmen/blob/dev/README.md#how-does-carmen-work)
-  [x] Write something up about how to use the sample app to demo and test the API. Perhaps this belongs in the readme, or perhaps it should go elsewhere
- [x] De-cruft the code and the API: check for orphaned code, unnecessary stuff in header files, anything that's likely to cause confusion about proper usage, etc.
- [x] Implement an option to enable iCloud backups for offline maps (the default is to disable backups)
- [x] MBXRasterTileOverlay's delegate property is weird. Make it normal.
- [x] MBXOfflineMapDownloader's delegate property is weird. Make it normal.
- [x] Make sure alloc/dealloc is solid for offline tile blob data coming from sqlite!

**Comment by vinod1988** [comment]
Hi mapbox team,

I am facing the issue in my app, when the user  come instant online we got the following assertion error, 
This is random behaviour, Please guide me how can i resolve this issue.

Console message:
Assertion failed: (_activeDataSessionTasks > 0), function -[MBXOfflineMapDownloader sqliteSaveDownloadedData:forURL:], file /Users/vinod/VINOD/RAW/PROJECTS/AGRALOGICS/SOURCE_CODE/agls-grower-app-ios/Agralogic/ThirdParty/MBXMapKit/MBXOfflineMapDownloader.m, line 442.

Mapbox library assertion break:

#pragma mark - Implementation: sqlite stuff

- (void)sqliteSaveDownloadedData:(NSData *)data forURL:(NSURL *)url
{
    assert(![NSThread isMainThread]);
    assert(_activeDataSessionTasks > 0);

Class name: MBXOfflineMapDownloader.

Please help me 
Thanks in advance

**Comment by incanus** [comment]
@vinod1988 It sounds like you might be trying to begin an offline map download without checking whether there is currently one in progress. Are you maybe kicking off a download resume yourself, when the library is also doing this automatically?
